# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  APPMAP: true
  APPLAND_API_KEY: "${{secrets.APPLAND_API_KEY}}"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "::set-output name=branch::$(echo ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"
      id: extract_branch
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Webpack install
      run: bundle exec rails webpacker:install
    - name: Webpacker Compile
      run: bundle exec rails webpacker:compile
    - name: Run tests
      run: bundle exec rake test
    - name: Output git rev
      run: git rev-parse HEAD
    - name: AppMap Analysis
      run: npx @appland/scanner ci --appmap-dir tmp/appmap  -C $(git rev-parse HEAD) -b ${{github.event.pull_request.head.ref}}
